#!/usr/bin/env python3
"""Generate compiled action metadata from the canonical action spec."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "specs" / "actions" / "actions.yaml"
OUTPUT = ROOT / "src" / "api" / "generated_action_metadata.inc"
PURPOSES = {
    "discover", "configure", "query", "inspect", "analyze", "trace",
    "verify", "export", "manage", "transform", "orchestrate",
}
FILLER_GUIDANCE = {
    "Tasks outside this action's documented contract.",
    "不要把本 action 用作不属于其已声明业务对象的查询；当前没有更近的公开替代 action。",
}


def normalized_sentence(value: str) -> str:
    return value.strip().rstrip(".。").casefold()


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def cpp_vector(values: list[str]) -> str:
    return "{" + ", ".join(cpp_string(value) for value in values) + "}"


def validate(entry: dict) -> None:
    name = entry["name"]
    if entry.get("status") not in {"experimental", "stable"}:
        raise ValueError(
            f"{name}: status must be experimental or stable"
        )
    for key in ("description_en", "description_zh"):
        if not isinstance(entry.get(key), str) or not entry[key].strip():
            raise ValueError(f"{name}: missing {key}")
    for key in ("purposes", "use_when", "do_not_use_when"):
        value = entry.get(key)
        if not isinstance(value, list) or not value or not all(
            isinstance(item, str) and item.strip() for item in value
        ):
            raise ValueError(f"{name}: {key} must be a non-empty string array")
    unknown = set(entry["purposes"]) - PURPOSES
    if unknown:
        raise ValueError(f"{name}: unsupported purposes {sorted(unknown)}")
    alternatives = entry.get("alternatives")
    if not isinstance(alternatives, list):
        raise ValueError(f"{name}: alternatives must be an array")
    for index, alternative in enumerate(alternatives):
        if (
            not isinstance(alternative, dict)
            or set(alternative) != {"action", "when"}
            or not all(isinstance(alternative[key], str) and alternative[key].strip()
                       for key in ("action", "when"))
        ):
            raise ValueError(
                f"{name}: alternatives[{index}] must contain non-empty action and when strings"
            )
    published = set(entry["use_when"]) | set(entry["do_not_use_when"])
    if published & FILLER_GUIDANCE:
        raise ValueError(f"{name}: generated fallback guidance is forbidden")
    description = normalized_sentence(entry["description_en"])
    if any(normalized_sentence(value) == description for value in entry["use_when"]):
        raise ValueError(
            f"{name}: use_when must state a decision boundary, not repeat description_en"
        )
    recommendations = entry.get("recommended_actions", [])
    if not isinstance(recommendations, list) or not all(
        isinstance(action, str) and action.strip()
        for action in recommendations
    ):
        raise ValueError(
            f"{name}: recommended_actions must be a string array"
        )
    if recommendations and recommendations[0] != "value.at":
        raise ValueError(
            f"{name}: first recommended action must be value.at"
        )
    if len(recommendations) != len(set(recommendations)):
        raise ValueError(
            f"{name}: recommended_actions must be unique"
        )
    forbidden = {
        "list.load", "list.create", "list.add", "list.delete",
    }
    for action in recommendations:
        if action in forbidden or ".config." in action:
            raise ValueError(
                f"{name}: configuration action cannot be recommended: {action}"
            )


def render() -> str:
    entries = json.loads(SPEC.read_text(encoding="utf-8"))["actions"]
    live_names = {entry["name"] for entry in entries}
    descriptions = {
        entry["name"]: entry["description_zh"] for entry in entries
    }
    lines = ["// Generated by tools/sync_action_metadata.py. Do not edit."]
    for entry in entries:
        validate(entry)
        for alternative in entry["alternatives"]:
            if alternative["action"] not in live_names:
                raise ValueError(
                    f"{entry['name']}: alternative targets unknown action "
                    f"{alternative['action']}"
                )
        for recommendation in entry.get("recommended_actions", []):
            if recommendation not in live_names:
                raise ValueError(
                    f"{entry['name']}: recommendation targets unknown action "
                    f"{recommendation}"
                )
        lines.extend([
            "{",
            "    ActionSpec spec;",
            f"    spec.name = {cpp_string(entry['name'])};",
            f"    spec.category = {cpp_string(entry['category'])};",
            "    spec.status = action_status_from_string("
            f"{cpp_string(entry['status'])});",
            "    spec.resource = resource_requirement_from_string("
            f"{cpp_string(entry['requires'])});",
            f"    spec.handler_kind = {cpp_string(entry['handler_kind'])};",
        ])
        lines.extend([
            f"    spec.request_schema = {cpp_string(entry['schemas']['request'])};",
            f"    spec.response_schema = {cpp_string(entry['schemas']['response'])};",
            f"    spec.request_examples = {cpp_vector(entry['examples']['request'])};",
            f"    spec.response_examples = {cpp_vector(entry['examples']['response'])};",
            f"    spec.args.required = {cpp_vector(entry.get('required_args', []))};",
            f"    spec.description_en = {cpp_string(entry['description_en'])};",
            f"    spec.description_zh = {cpp_string(entry['description_zh'])};",
            f"    spec.purposes = {cpp_vector(entry['purposes'])};",
            f"    spec.use_when = {cpp_vector(entry['use_when'])};",
            f"    spec.do_not_use_when = {cpp_vector(entry['do_not_use_when'])};",
            "    spec.alternatives = Json::array();",
        ])
        for alternative in entry["alternatives"]:
            lines.append(
                "    spec.alternatives.push_back({"
                f'{{"action", {cpp_string(alternative["action"])} }}, '
                f'{{"when", {cpp_string(alternative["when"])} }}'
                "});"
            )
        for recommendation in entry.get("recommended_actions", []):
            lines.extend([
                "    {",
                "        ActionRecommendation recommendation;",
                f"        recommendation.action = {cpp_string(recommendation)};",
                "        recommendation.purpose = "
                f"{cpp_string(descriptions[recommendation])};",
                "        spec.recommended_actions.push_back(recommendation);",
                "    }",
            ])
        for variant in entry.get("resource_variants", []):
            lines.extend([
                "    {",
                "        ResourceVariant variant;",
                f"        variant.name = {cpp_string(variant['name'])};",
                "        variant.resource = resource_requirement_from_string("
                f"{cpp_string(variant['requires'])});",
                f"        variant.required_args = {cpp_vector(variant.get('required_args', []))};",
                f"        variant.forbidden_args = {cpp_vector(variant.get('forbidden_args', []))};",
                "        spec.resource_variants.push_back(variant);",
                "    }",
            ])
        lines.extend(["    registry.register_spec(spec);", "}"])
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"stale generated action metadata: {OUTPUT.relative_to(ROOT)}")
            return 1
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
