#!/usr/bin/env python3
"""Generate the single embedded xdebug help payload."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "help.txt"
OUTPUT = ROOT / "src" / "api" / "generated_help_text.inc"


def render() -> str:
    text = SOURCE.read_text(encoding="utf-8")
    text = re.sub(
        r"^[ \t]*# xdebug-example:[^:\n]+:(?:begin|end)[ \t]*\n?",
        "",
        text,
        flags=re.MULTILINE,
    )
    return (
        "// Generated by tools/sync_help_text.py. Do not edit.\n"
        + json.dumps(text, ensure_ascii=False)
        + "\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    generated = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit(
                "ERROR: generated help payload is stale; "
                "run xdebug/tools/sync_help_text.py"
            )
        print("embedded help payload is synchronized")
        return 0
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
